title: Deep Cafe
email: hello@deep.cafe
description: "Powered by curiosity and intrigue."

domain: deep.cafe
url: https://www.deep.cafe

permalink: /:categories/:title
date_format: "%d %b %Y"
month_date_format: "%b %Y"
excerpt_separator: <!--more-->

plugins:
  - jekyll-loading-lazy
